settings:
    index:
        # single node, no sharding
        number_of_shards: 1
        number_of_replicas: 0
mappings:
    properties:
            title:
                type: text
            description:
                type: text
            content:
                type: text
